global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "mlops-api"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "mlflow"
    scrape_interval: 30s
    static_configs:
      - targets: ["mlflow_server:5000"]
